# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35964d4297701afe66c3512c9ee0fc6c0bad86f5915ef0abba4938b2246721b4a58da6d14b786dda7f7924937e49ffd20b0c4a1f4bc4c5993a51e20ef2fb0b9f

test:
  secret_key_base: f74eb46ee30550601ee23301bf48211e5b54b334105ef9e0117df4bb4e55e701c493bede0b515ff6646f793af2ca899bf36e04618bed984198d1485bc281e965

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
